# .github/workflows/reusable-ci-pipeline.yml
name: Reusable CI Pipeline for Java Microservice

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.service_path }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build and run tests with Gradle
        run: ./gradlew build --no-daemon

      - name: Build Docker image
        if: success()
        run: |
          if [ -f "Dockerfile" ]; then
            docker build -t ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}:${{ github.sha }} .
          else
            echo "No Dockerfile found, skipping Docker build"
          fi
